/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.system.evaluator;

import com.system.LoginPage;
import com.system.controller.LoginController;
import com.system.utils.Utils;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author tapas
 */
public class EvaluatorDashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    JPanel mainPanel;
    int userID;
    public EvaluatorDashboard(JPanel mainPanel, int userID) {
        initComponents();
        this.mainPanel = mainPanel;
        this.userID = userID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPlant = new javax.swing.JButton();
        btnPlant1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Evaluator Dashboard");

        btnPlant.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnPlant.setText("Active Inspections");
        btnPlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlantActionPerformed(evt);
            }
        });

        btnPlant1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnPlant1.setText("Past Inspections");
        btnPlant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlant1ActionPerformed(evt);
            }
        });

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlant1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(211, 211, 211))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jButton1)
                .addGap(58, 58, 58)
                .addComponent(btnPlant)
                .addGap(80, 80, 80)
                .addComponent(btnPlant1)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlantActionPerformed
        mainPanel.add(new ActiveInspections(mainPanel, userID));
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.next(mainPanel);
    }//GEN-LAST:event_btnPlantActionPerformed

    private void btnPlant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlant1ActionPerformed
        mainPanel.add(new PastInspections(mainPanel));
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.next(mainPanel);
    }//GEN-LAST:event_btnPlant1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginController loginController = new LoginController();
        mainPanel.add(new LoginPage(mainPanel, loginController));
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.next(mainPanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlant;
    private javax.swing.JButton btnPlant1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
