/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.system.plant_manager;

import com.system.models.Equipment;
import com.system.models.Plant;
import com.system.utils.Utils;
import java.util.List;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tapas
 */
public class PlantDetails extends javax.swing.JPanel {

    /**
     * Creates new form PlantDetails
     */
    JPanel mainPanel;
    Plant currentPlant;
    List<Equipment> equipments;
    PlantManagerController controller = new PlantManagerController();
    public PlantDetails(JPanel mainPanel, Plant currentPlant) {
        initComponents();
        this.mainPanel = mainPanel;
        this.currentPlant = currentPlant;
        populate();
    }
    
    void populate(){
        lblPlant.setText(currentPlant.getName());
        equipments = controller.fetchPlantEquipments(currentPlant.getId());
        populateTable();
    }
     void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblEquipments.getModel();
        model.setRowCount(0);
        for (Equipment e : equipments) {
            Vector<String> row = new Vector<String>();
            row.add("" + e.getId());
            row.add(e.getTag());
            row.add(e.getEquipmentName());
            row.add(e.getIsWorking() == 1 ? "Yes" : "No");
            row.add(e.getRemark());
            model.addRow(row);
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblPlant = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEquipments = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 51, 102));

        btnBack.setText("← Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPlant.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPlant.setForeground(new java.awt.Color(255, 255, 255));
        lblPlant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlant.setText("Plant Details");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Installed Equipments");

        tblEquipments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tag", "Name", "Working?", "Remark"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEquipments);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnBack)
                        .addGap(65, 65, 65)
                        .addComponent(lblPlant, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlant)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Utils.goBack(mainPanel, this);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPlant;
    private javax.swing.JTable tblEquipments;
    // End of variables declaration//GEN-END:variables
}
