/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.system.inspector;


import com.system.models.Inspection;
import com.system.utils.Utils;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ViewReport extends javax.swing.JPanel {

    /**
     * Creates new form ViewReport
     */
     JPanel mainPanel;
    List<Inspection> inspections;
    final InspectorController controller = new InspectorController();
    Inspection Currentinspection = null;
    
   
    public ViewReport(JPanel mainPanel) {
        initComponents();
        this.mainPanel = mainPanel;
        populateInspections();
           
    }
   void populateInspections(){
        inspections = controller.fetchInspections();
        populateTable();
    }
void populateTable(){
    DefaultTableModel model = (DefaultTableModel) tblInspection.getModel();
        model.setRowCount(0);
        // SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        for (Inspection inspection : inspections) {
            Vector<String> row = new Vector<String>();
            row.add("" + inspection.getId());
           // row.add(""+ dateFormat.format(inspection.getInspection_date()));
           row.add("" + inspection.getInspection_date());
            row.add("" + inspection.getRemark());
            row.add("" + inspection.getPlant_Id());
            row.add("" + inspection.getInspector_id());
            row.add("" + inspection.getEvaluator_id());
            row.add("" + inspection.getEvaluator_remark());         
            model.addRow(row);
        }
        tblInspection.setModel(model);
        //txtName.setText("");
        //Currentinspection = null;
       // btnAddPlant.setText("Add New Plant");
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInspection = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        tblInspection.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Inspection_Date", "Remark", "Plant_ID", "Inspector_ID", "Evaluator_ID", "Evaluator_Remark"
            }
        ));
        jScrollPane1.setViewportView(tblInspection);

        btnBack.setText("← Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Utils.goBack(mainPanel, this);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInspection;
    // End of variables declaration//GEN-END:variables
}
