/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.system.admin;

import com.system.LoginPage;
import com.system.controller.LoginController;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sid
 */
public class AdminDashboard extends javax.swing.JPanel {
JPanel mainPanel;
    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminLabel = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        btnViewUser = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnUserReports = new javax.swing.JButton();

        AdminLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AdminLabel.setText("Admin Dashboard");

        btnAddUser.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnAddUser.setText("Add Users");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnViewUser.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnViewUser.setText("View Users");
        btnViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUserActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnUserReports.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnUserReports.setText("User Reports");
        btnUserReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUserReports, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addComponent(AdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(btnAddUser)
                .addGap(45, 45, 45)
                .addComponent(btnViewUser)
                .addGap(48, 48, 48)
                .addComponent(btnUserReports)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        mainPanel.add(new CRUDAdmin(mainPanel, null));
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.next(mainPanel);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUserActionPerformed
        // TODO add your handling code here:
        mainPanel.add(new ViewUser(mainPanel));
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.next(mainPanel);
    }//GEN-LAST:event_btnViewUserActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginController loginController = new LoginController();
        mainPanel.add(new LoginPage(mainPanel, loginController));
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.next(mainPanel);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUserReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserReportsActionPerformed
        // TODO add your handling code here:
        mainPanel.add(new ViewUserReport(mainPanel));
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.next(mainPanel);
    }//GEN-LAST:event_btnUserReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUserReports;
    private javax.swing.JButton btnViewUser;
    // End of variables declaration//GEN-END:variables
}
