/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.system.admin;

import com.system.models.users.User;
import com.system.utils.DatabaseHelper;
import com.system.utils.PDFUtil;
import com.system.utils.Utils;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sid
 */
public class ViewUserReport extends javax.swing.JPanel {
private JPanel mainPanel;
List<User> users = new ArrayList<>();
final AdminController controller = new AdminController();
User user; 
    /**
     * Creates new form ViewUserReport
     */
    public ViewUserReport(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        initComponents();
        populateUsers();
    }
    
    void populateUsers() {
        String userType = cmbViewUser.getSelectedItem().toString();
        int roleid = Utils.getroleid(userType);
        users = controller.fetchUsers(roleid);
        populateTable();
    }
    
    void populateTable() {
        DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[7];
        for(User user : users){
            rowData[0] = user.getId();
            rowData[1] = user.getName();
            rowData[2] = user.getGender();
            rowData[3] = user.getDob();
            rowData[4] = user.getEmail();
            model.addRow(rowData);
        }  
        UserTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelViewuserReport = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        cmbViewUser = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 102));
        setForeground(new java.awt.Color(255, 255, 255));

        LabelViewuserReport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelViewuserReport.setForeground(new java.awt.Color(255, 255, 255));
        LabelViewuserReport.setText("User Reports");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "DOB", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UserTable.setRowHeight(30);
        jScrollPane1.setViewportView(UserTable);

        cmbViewUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User", "Plant Manager", "Inspector", "Evaluator" }));
        cmbViewUser.setToolTipText("Select User");
        cmbViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbViewUserActionPerformed(evt);
            }
        });

        jButton1.setText("Generate All User Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Single User Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(140, 140, 140)
                        .addComponent(LabelViewuserReport)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelViewuserReport)
                    .addComponent(btnBack))
                .addGap(36, 36, 36)
                .addComponent(cmbViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         Utils.goBack(mainPanel, this);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbViewUserActionPerformed
        // TODO add your handling code here:
        populateUsers();
    }//GEN-LAST:event_cmbViewUserActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(UserTable.getSelectedRow() < 0){
            Utils.showDialog(this, null, "Please select a User...");
        }else{
            User u = users.get(UserTable.getSelectedRow());
            PDFUtil.generatePDF(this, u.getName(), u.getName(), 
                    DatabaseHelper.getInstance()
                            .fetchData("SELECT * FROM sql5694823.user WHERE id="+u.getId()));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch(cmbViewUser.getSelectedIndex()){
            case 0:
                Utils.showDialog(this, null,"Please select an User Type");
                break;
            case 1:
                PDFUtil.generatePDF(this, "Plant Managers", "Plant Managers", 
                    DatabaseHelper.getInstance()
                            .fetchData("SELECT * FROM sql5694823.user WHERE role_id="+2));
                break;
            case 2:
                PDFUtil.generatePDF(this, "Inspectors", "Inspectors", 
                    DatabaseHelper.getInstance()
                            .fetchData("SELECT * FROM sql5694823.user WHERE role_id="+3));
                break;
            case 3:
                PDFUtil.generatePDF(this, "Evaluators", "Evaluators", 
                    DatabaseHelper.getInstance()
                            .fetchData("SELECT * FROM sql5694823.user WHERE role_id="+4));
                break;
            default:
                Utils.showDialog(this, null,"Invalid Choice...");
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelViewuserReport;
    private javax.swing.JTable UserTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbViewUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
